main: me.markeh.ffw.FreshWilderness
name: FreshWilderness
version: 1.2.0
website: http://ma.rkhugh.es/freshwilderness
authors: [ MarkehMe ]
description: §eFresh Wilderness keeps your wilderness fresh.§aMarkehMe §eis the lead programmer. See §bhttp://ma.rkhugh.es/freshwilderness§e for more information.
softdepend: [ FactionsFramework ]
